version: 3
tasks:
  bump:
    vars:
      VERSION:
        sh: yq '.project.version' pyproject.toml
    cmds:
      - git add pyproject.toml
      - 'git commit -m "bump: {{.VERSION}}"'
      - 'git tag "v{{.VERSION}}" -m "v{{.VERSION}}"'

  fmt:
    cmd: clang-format -i src/bencode_c/*.c src/bencode_c/*.h

  build:
    deps:
      - build:windows
      - build:linux

  build:windows:
    silent: true
    internal: true
    platforms:
      - windows
    sources:
      - setup.py
      - ./src/bencode_c/*.c
      - ./src/bencode_c/*.h
    generates:
      - ./src/**/*.pyd
    cmds:
      - cmd: python setup.py build_ext --inplace

  build:linux:
    silent: true
    internal: true
    platforms:
      - linux
    sources:
      - setup.py
      - ./src/bencode_c/*.c
      - ./src/bencode_c/*.h
    generates:
      - ./src/**/*.so
    cmds:
      - cmd: python setup.py build_ext --inplace

  dev:
    sources:
      - src/**/*.c
      - src/**/*.h
      - src/**/*.py
      - tests/**/*.py
      - tests/*.py
      - "*.py"
    generates:
      - src/**/*.so
      - src/**/*.pyd
    deps:
      - build:dev
    env:
      #      CFLAGS: "-O0 -g"
      PYTHONPATH: src
      # LD_PRELOAD: libclang_rt.asan.so
    cmds:
      - python -X faulthandler -c 'import bencode_c'
      - pytest -x -v -s
      - task: build:inplace
      - cmd: python -X faulthandler a.py

  test:
    sources:
      - src/**/*
      - tests/**/*
    deps:
      - build
    env:
      PYTHONPATH: src
    cmds:
      - pytest -x -v -s
