version: 3
tasks:
  build:
    cmds:
      - cmd: python setup.py build wheel
  bump:
    vars:
      VERSION:
        sh: yq '.project.version' pyproject.toml
    cmds:
      - git add pyproject.toml
      - 'git commit -m "bump: {{.VERSION}}"'
      - 'git tag "v{{.VERSION}}" -m "v{{.VERSION}}"'

  dev:build:
    sources:
      - src/**/*.c
      - src/**/*.h
    generates:
      - src/**/*.so
      - src/**/*.pyd
    cmds:
      - cmd: python setup.py build_ext --force --inplace
        silent: true

  dev:
    sources:
      - src/**/*.c
      - src/**/*.h
      - src/**/*.py
      - tests/**/*.py
      - tests/*.py
      - "*.py"
    generates:
      - src/**/*.so
      - src/**/*.pyd
    env:
      HPY: trace
      CFLAGS: "-O0 -g"
      # LD_PRELOAD: libclang_rt.asan.so
    cmds:
      - cmd: python setup.py build_ext --force --inplace
        silent: true
      - PYTHONPATH=src python -X faulthandler a.py
#      - pytest -x -v -s
